
/*
async function getMovies() {
  let movies = await (await fetch('http://localhost:5600/api/movies')).json();
  console.log(movies)
}

async function lookAtMovie(movieTitle) {
  window.sessionStorage.setItem("filterMovie", JSON.stringify(movieTitle));

  history.pushState(null, null, "/findScreening");
  router();


getMovies()
*/

const movies = [
  {
    "imDbId": "tt0050083",
    "title": "12 Angry Men",
    "fullTitle": "12 Angry Men (1957)",
    "type": "Movie",
    "year": "1957",
    "videoId": "vi3452609817",
    "videoTitle": "12 Angry Men",
    "videoDescription": "Three Reasons Criterion trailer",
    "plot": "The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father. What begins as an open-and-shut case of murder soon becomes a detective story that presents a succession of clues creating doubt, and a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, AND each other. Based on the play, all of the action takes place on the stage of the jury room.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNjE3MWNhZDYtYjFlMS00MzM4LTg5M2YtYTAwMGY2ZDg0OGY0XkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3452609817",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3452609817/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0111161",
    "title": "The Shawshank Redemption",
    "fullTitle": "The Shawshank Redemption (1994)",
    "type": "Movie",
    "year": "1994",
    "videoId": "vi3877612057",
    "videoTitle": "Official Trailer",
    "videoDescription": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.\r\n",
    "plot": "Chronicles the experiences of a formerly successful banker as a prisoner in the gloomy jailhouse of Shawshank after being found guilty of a crime he did not commit. The film portrays the man's unique way of dealing with his new, torturous life; along the way he befriends a number of fellow prisoners, most notably a wise long-term inmate named Red.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNjQ2NDA3MDcxMF5BMl5BanBnXkFtZTgwMjE5NTU0NzE@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3877612057",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3877612057/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0071562",
    "title": "The Godfather: Part II",
    "fullTitle": "The Godfather: Part II (1974)",
    "type": "Movie",
    "year": "1974",
    "videoId": "vi696162841",
    "videoTitle": "The Godfather: Part II",
    "videoDescription": "Trailer for The Godfather: Part II",
    "plot": "The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNWE4YzY4OGMtZDM5YS00YWVkLTgwMDktNzVmOGU3NjEwMjNlXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi696162841",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi696162841/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0068646",
    "title": "The Godfather",
    "fullTitle": "The Godfather (1972)",
    "type": "Movie",
    "year": "1972",
    "videoId": "vi1348706585",
    "videoTitle": "Official Trailer ",
    "videoDescription": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    "plot": "The Godfather \"Don\" Vito Corleone is the head of the Corleone mafia family in New York. He is at the event of his daughter's wedding. Michael, Vito's youngest son and a decorated WW II Marine is also present at the wedding. Michael seems to be uninterested in being a part of the family business. Vito is a powerful man, and is kind to all those who give him respect but is ruthless against those who do not. But when a powerful and treacherous rival wants to sell drugs and needs the Don's influence for the same, Vito refuses to do it. What follows is a clash between Vito's fading old values and the new ways which may cause Michael to do the thing he was most reluctant in doing and wage a mob war against all the other mafia families which could tear the Corleone family apart.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYWNlN2U4YjQtMzI3NC00ZjkxLWEwMTItYWRlNDUxYTYwYjVlXkEyXkFqcGdeQWpvaG5oYXJ0._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1348706585",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1348706585/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0108052",
    "title": "Schindler's List",
    "fullTitle": "Schindler's List (1993)",
    "type": "Movie",
    "year": "1993",
    "videoId": "vi1158527769",
    "videoTitle": "25th Anniversary Trailer",
    "videoDescription": "25th Anniversary Release Trailer",
    "plot": "Oskar Schindler is a vain and greedy German businessman who becomes an unlikely humanitarian amid the barbaric German Nazi reign when he feels compelled to turn his factory into a refuge for Jews. Based on the true story of Oskar Schindler who managed to save about 1100 Jews from being gassed at the Auschwitz concentration camp, it is a testament to the good in all of us.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BOTIxMTUzMmUtODU2MS00MDhjLTlmMGQtMzNhZTFhOTI5ZjE5XkEyXkFqcGdeQXRoaXJkLXBhcnR5LXZpZGVvLXVwZGF0ZXI@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1158527769",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1158527769/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0167260",
    "title": "The Lord of the Rings: The Return of the King",
    "fullTitle": "The Lord of the Rings: The Return of the King (2003)",
    "type": "Movie",
    "year": "2003",
    "videoId": "vi718127897",
    "videoTitle": "Official Trailer",
    "videoDescription": "Gandalf and Aragorn lead the World of Men against Sauron&apos;s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    "plot": "The final confrontation between the forces of good and evil fighting for control of the future of Middle-earth. Frodo and Sam reach Mordor in their quest to destroy the One Ring, while Aragorn leads the forces of good against Sauron's evil army at the stone city of Minas Tirith.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNDRmNjQxOWItNTY3MS00M2ExLWJiYWYtNGQ2OTI5MWRkYWFlXkEyXkFqcGdeQWxiaWFtb250._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi718127897",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi718127897/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0060196",
    "title": "The Good, the Bad and the Ugly",
    "fullTitle": "The Good, the Bad and the Ugly (1966)",
    "type": "Movie",
    "year": "1966",
    "videoId": "vi3416964889",
    "videoTitle": "The Good, the Bad and the Ugly",
    "videoDescription": "Official Trailer",
    "plot": "Blondie, The Good (Clint Eastwood), is a professional gunslinger who is out trying to earn a few dollars. Angel Eyes, The Bad (Lee Van Cleef), is a hitman who always commits to a task and sees it through--as long as he's paid to do so. And Tuco, The Ugly (Eli Wallach), is a wanted outlaw trying to take care of his own hide. Tuco and Blondie share a partnership making money off of Tuco's bounty, but when Blondie unties the partnership, Tuco tries to hunt down Blondie. When Blondie and Tuco come across a horse carriage loaded with dead bodies, they soon learn from the only survivor, Bill Carson (Antonio Casale), that he and a few other men have buried a stash of gold in a cemetery. Unfortunately, Carson dies and Tuco only finds out the name of the cemetery, while Blondie finds out the name on the grave. Now the two must keep each other alive in order to find the gold. Angel Eyes (who had been looking for Bill Carson) discovers that Tuco and Blondie met with Carson and knows they know where the gold is; now he needs them to lead him to it. Now The Good, the Bad, and the Ugly must all battle it out to get their hands on $200,000.00 worth of gold.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYjJmYTNmZDItNjExOS00MmY3LWEwMjgtNjQ3M2M2YjA1MDRkXkEyXkFqcGdeQTNwaW5nZXN0._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3416964889",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3416964889/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0120737",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "fullTitle": "The Lord of the Rings: The Fellowship of the Ring (2001)",
    "type": "Movie",
    "year": "2001",
    "videoId": "vi684573465",
    "videoTitle": "Official Trailer",
    "videoDescription": "A shy young hobbit named Frodo Baggins inherits a simple gold ring. He knows the ring has power, but not that he alone holds the secret to the survival--or enslavement--of the entire world. Now Frodo, accompanied by a wizard, an elf, a dwarf, two men and three loyal hobbit friends, must become the greatest hero the world has ever known to save the land and the people he loves.",
    "plot": "An ancient Ring thought lost for centuries has been found, and through a strange twist of fate has been given to a small Hobbit named Frodo. When Gandalf discovers the Ring is in fact the One Ring of the Dark Lord Sauron, Frodo must make an epic quest to the Cracks of Doom in order to destroy it. However, he does not go alone. He is joined by Gandalf, Legolas the elf, Gimli the Dwarf, Aragorn, Boromir, and his three Hobbit friends Merry, Pippin, and Samwise. Through mountains, snow, darkness, forests, rivers and plains, facing evil and danger at every corner the Fellowship of the Ring must go. Their quest to destroy the One Ring is the only hope for the end of the Dark Lords reign.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMzQ2YjI2YzgtZmNmMy00ZjUyLWE0NGItY2Y3NjUzZWM4NmM3XkEyXkFqcGdeQWxiaWFtb250._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi684573465",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi684573465/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0109830",
    "title": "Forrest Gump",
    "fullTitle": "Forrest Gump (1994)",
    "type": "Movie",
    "year": "1994",
    "videoId": "vi3567517977",
    "videoTitle": "Forrest Gump",
    "videoDescription": "Trailer 1 for Forrest Gump",
    "plot": "Forrest Gump is a simple man with a low I.Q. but good intentions. He is running through childhood with his best and only friend Jenny. His 'mama' teaches him the ways of life and leaves him to choose his destiny. Forrest joins the army for service in Vietnam, finding new friends called Dan and Bubba, he wins medals, creates a famous shrimp fishing fleet, inspires people to jog, starts a ping-pong craze, creates the smiley, writes bumper stickers and songs, donates to people and meets the president several times. However, this is all irrelevant to Forrest who can only think of his childhood sweetheart Jenny Curran, who has messed up her life. Although in the end all he wants to prove is that anyone can love anyone.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYzQyMWQ1ODMtZGE2OS00YzQyLWE2OWYtZmU5OGFiMWMwYmIyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3567517977",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3567517977/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt1375666",
    "title": "Inception",
    "fullTitle": "Inception (2010)",
    "type": "Movie",
    "year": "2010",
    "videoId": "vi2959588889",
    "videoTitle": "10th Anniversary Dream Trailer",
    "videoDescription": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.\r\n\r\n",
    "plot": "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMTQ1ZmIzOTAtNDcwZi00NDVkLWE4NWItYWNhZGY1MmVlZGU0XkEyXkFqcGdeQWRvb2xpbmhk._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2959588889",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2959588889/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0102926",
    "title": "The Silence of the Lambs",
    "fullTitle": "The Silence of the Lambs (1991)",
    "type": "Movie",
    "year": "1991",
    "videoId": "vi3377380121",
    "videoTitle": "Official Trailer",
    "videoDescription": "",
    "plot": "F.B.I. trainee Clarice Starling (Jodie Foster) works hard to advance her career, while trying to hide or put behind her West Virginia roots, of which if some knew, would automatically classify her as being backward or white trash. After graduation, she aspires to work in the agency's Behavioral Science Unit under the leadership of Jack Crawford (Scott Glenn). While she is still a trainee, Crawford asks her to question Dr. Hannibal Lecter (Sir Anthony Hopkins), a psychiatrist imprisoned, thus far, for eight years in maximum security isolation for being a serial killer who cannibalized his victims. Clarice is able to figure out the assignment is to pick Lecter's brains to help them solve another serial murder case, that of someone coined by the media as \"Buffalo Bill\" (Ted Levine), who has so far killed five victims, all located in the eastern U.S., all young women, who are slightly overweight (especially around the hips), all who were drowned in natural bodies of water, and all who were stripped of large swaths of skin. She also figures that Crawford chose her, as a woman, to be able to trigger some emotional response from Lecter. After speaking to Lecter for the first time, she realizes that everything with him will be a psychological game, with her often having to read between the very cryptic lines he provides. She has to decide how much she will play along, as his request in return for talking to him is to expose herself emotionally to him. The case takes a more dire turn when a sixth victim is discovered, this one from who they are able to retrieve a key piece of evidence, if Lecter is being forthright as to its meaning. A potential seventh victim is high profile Catherine Martin (Brooke Smith), the daughter of Senator Ruth Martin (Diane Baker), which places greater scrutiny on the case as they search for a hopefully still alive Catherine. Who may factor into what happens is Dr. Frederick Chilton (Anthony Heald), the warden at the prison, an opportunist who sees the higher profile with Catherine, meaning a higher profile for himself if he can insert himself successfully into the proceedings.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BN2ZiYzIyMWQtNDUyNy00YmExLWIwNmMtN2FhNzFiODgyYmU4XkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3377380121",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3377380121/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0110912",
    "title": "Pulp Fiction",
    "fullTitle": "Pulp Fiction (1994)",
    "type": "Movie",
    "year": "1994",
    "videoId": "vi2620371481",
    "videoTitle": "Official Trailer",
    "videoDescription": "The lives of two mob hit men, a boxer, a gangster&apos;s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    "plot": "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hit men who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMjI5MzgxMTQ4M15BMl5BanBnXkFtZTgwNjczMTk0NzE@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2620371481",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2620371481/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0468569",
    "title": "The Dark Knight",
    "fullTitle": "The Dark Knight (2008)",
    "type": "Movie",
    "year": "2008",
    "videoId": "vi324468761",
    "videoTitle": "DVD Trailer",
    "videoDescription": "Trailer for Blu-ray/DVD release of most recent Batman installment",
    "plot": "Set within a year after the events of Batman Begins (2005), Batman, Lieutenant James Gordon, and new District Attorney Harvey Dent successfully begin to round up the criminals that plague Gotham City, until a mysterious and sadistic criminal mastermind known only as \"The Joker\" appears in Gotham, creating a new wave of chaos. Batman's struggle against The Joker becomes deeply personal, forcing him to \"confront everything he believes\" and improve his technology to stop him. A love triangle develops between Bruce Wayne, Dent, and Rachel Dawes.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNWJkYWJlOWMtY2ZhZi00YWM0LTliZDktYmRiMGYwNzczMTZhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi324468761",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi324468761/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0133093",
    "title": "The Matrix",
    "fullTitle": "The Matrix (1999)",
    "type": "Movie",
    "year": "1999",
    "videoId": "vi1032782617",
    "videoTitle": "Theatrical Trailer",
    "videoDescription": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. ",
    "plot": "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. As a rebel against the machines, Neo must confront the agents: super-powerful computer programs devoted to stopping Neo and the entire human rebellion.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNDQ4NTRmN2ItYjgzMS00MzY3LWEwNmYtYmE2ODllZDdhNGI1XkEyXkFqcGdeQXdvbmtpbQ@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1032782617",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1032782617/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0099685",
    "title": "Goodfellas",
    "fullTitle": "Goodfellas (1990)",
    "type": "Movie",
    "year": "1990",
    "videoId": "vi2673654553",
    "videoTitle": "Official Trailer",
    "videoDescription": "",
    "plot": "Henry Hill might be a small time gangster, who may have taken part in a robbery with Jimmy Conway and Tommy De Vito, two other gangsters who might have set their sights a bit higher. His two partners could kill off everyone else involved in the robbery, and slowly start to think about climbing up through the hierarchy of the Mob. Henry, however, might be badly affected by his partners' success, but will he consider stooping low enough to bring about the downfall of Jimmy and Tommy?",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BZWMyMjYwY2QtMDMxMC00ZmY3LTgwZGMtYzc3ZTgyZjQ4NDMwXkEyXkFqcGdeQUlNRGJWaWRlb1RodW1ibmFpbFNlcnZpY2U@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2673654553",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2673654553/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0816692",
    "title": "Interstellar",
    "fullTitle": "Interstellar (2014)",
    "type": "Movie",
    "year": "2014",
    "videoId": "vi1586278169",
    "videoTitle": "Trailer #4",
    "videoDescription": "A group of explorers make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.\r\n",
    "plot": "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel. A newly discovered wormhole in the far reaches of our solar system allows a team of astronauts to go where no man has gone before, a planet that may have the right environment to sustain human life.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNjM5OTQzMTg4N15BMl5BanBnXkFtZTgwOTgyMjM0NTE@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1586278169",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1586278169/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0137523",
    "title": "Fight Club",
    "fullTitle": "Fight Club (1999)",
    "type": "Movie",
    "year": "1999",
    "videoId": "vi781228825",
    "videoTitle": "Fight Club",
    "videoDescription": "Trailer for Fight Club",
    "plot": "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter), another fake attendee of support groups, his life seems to become a little more bearable. However when he associates himself with Tyler (Brad Pitt) he is dragged into an underground fight club and soap making scheme. Together the two men spiral out of control and engage in competitive rivalry for love and power.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMTNmYzllNWYtYzU1Yi00YWFmLTgwMzMtZmY4OGE3NzExNzEzXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi781228825",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi781228825/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0076759",
    "title": "Star Wars: Episode IV - A New Hope",
    "fullTitle": "Star Wars: Episode IV - A New Hope (1977)",
    "type": "Movie",
    "year": "1977",
    "videoId": "vi1317709849",
    "videoTitle": "Original Teaser Trailer",
    "videoDescription": "Watch the original teaser trailer for Star Wars.",
    "plot": "The Imperial Forces, under orders from cruel Darth Vader, hold Princess Leia hostage in their efforts to quell the rebellion against the Galactic Empire. Luke Skywalker and Han Solo, captain of the Millennium Falcon, work together with the companionable droid duo R2-D2 and C-3PO to rescue the beautiful princess, help the Rebel Alliance and restore freedom and justice to the Galaxy.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMTUzNDY0NjY4Nl5BMl5BanBnXkFtZTgwNjY4MTQ0NzE@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1317709849",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1317709849/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0118799",
    "title": "Life Is Beautiful",
    "fullTitle": "Life Is Beautiful (1997)",
    "type": "Movie",
    "year": "1997",
    "videoId": "vi2332801561",
    "videoTitle": "Trailer originale italiano [OV]",
    "videoDescription": "",
    "plot": "In 1930s Italy, a carefree Jewish waiter named Guido starts a fairy tale life by courting and marrying a lovely woman from a nearby city. Guido and his wife have a son and live happily together until the occupation of Italy by German forces. In an attempt to hold his family together and help his son survive the horrors of a Jewish Concentration Camp, Guido imagines that the Holocaust is a game and that the grand prize for winning is a tank.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNzA1MmVhYjQtZTJiYi00YTRkLWExOTUtODFlNDQ0YzMzZjJlXkEyXkFqcGdeQWpvaG5oYXJ0._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2332801561",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2332801561/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0120689",
    "title": "The Green Mile",
    "fullTitle": "The Green Mile (1999)",
    "type": "Movie",
    "year": "1999",
    "videoId": "vi552796441",
    "videoTitle": "The Green Mile",
    "videoDescription": "Home Video Trailer from Warner Home Video",
    "plot": "Death Row guards at a penitentiary, in the 1930's, have a moral dilemma with their job when they discover one of their prisoners, a convicted murderer, has a special gift.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BODU4NmYyMzEtNzkwNy00NmFlLTk3YWItM2I5NDk3YTUyODFhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi552796441",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi552796441/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0047478",
    "title": "Seven Samurai",
    "fullTitle": "Seven Samurai (1954)",
    "type": "Movie",
    "year": "1954",
    "videoId": "vi2923348761",
    "videoTitle": "Trailer",
    "videoDescription": "A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.",
    "plot": "A veteran samurai, who has fallen on hard times, answers a village's request for protection from bandits. He gathers 6 other samurai to help him, and they teach the townspeople how to defend themselves, and they supply the samurai with three small meals a day. The film culminates in a giant battle when 40 bandits attack the village.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYTA0ZjczYTctNDUwYi00MmM5LWE4YjAtODI5NWRiMzFhNjFhXkEyXkFqcGdeQXRyYW5zY29kZS13b3JrZmxvdw@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2923348761",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2923348761/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0317248",
    "title": "City of God",
    "fullTitle": "City of God (2002)",
    "type": "Movie",
    "year": "2002",
    "videoId": "vi1783208985",
    "videoTitle": "City of God: Blu-Ray",
    "videoDescription": "Trailer for City Of God",
    "plot": "Brazil, 1960s, City of God. The Tender Trio robs motels and gas trucks. Younger kids watch and learn well...too well. 1970s: Li'l Zé has prospered very well and owns the city. He causes violence and fear as he wipes out rival gangs without mercy. His best friend Bené is the only one to keep him on the good side of sanity. Rocket has watched these two gain power for years, and he wants no part of it. he keeps getting swept up in the madness. All he wants to do is take pictures. 1980s: Things are out of control between the last two remaining gangs...will it ever end? Welcome to the City of God.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNTQzY2M4ZTctZWRjZS00NzlmLWI4YzgtMDUzZGU5YjlmYzkxXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1783208985",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1783208985/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0114369",
    "title": "Se7en",
    "fullTitle": "Se7en (1995)",
    "type": "Movie",
    "year": "1995",
    "videoId": "vi2508831257",
    "videoTitle": "Official Trailer",
    "videoDescription": "",
    "plot": "A film about two homicide detectives' (Morgan Freeman and Brad Pitt) desperate hunt for a serial killer who justifies his crimes as absolution for the world's ignorance of the Seven Deadly Sins. The movie takes us from the tortured remains of one victim to the next as the sociopathic \"John Doe\" (Kevin Spacey) sermonizes to Detectives Somerset and Mills -- one sin at a time. The sin of Gluttony comes first and the murderer's terrible capacity is graphically demonstrated in the dark and subdued tones characteristic of film noir. The seasoned and cultured but jaded Somerset researches the Seven Deadly Sins in an effort to understand the killer's modus operandi while the bright but green and impulsive Detective Mills (Pitt) scoffs at his efforts to get inside the mind of a killer...",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BZmMxNmJiYzctNGRkZC00YzcxLTgyNjMtMmIxZWVlNDA4ZWRjXkEyXkFqcGdeQXRodW1ibmFpbC1pbml0aWFsaXplcg@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2508831257",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2508831257/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0080684",
    "title": "Star Wars: Episode V - The Empire Strikes Back",
    "fullTitle": "Star Wars: Episode V - The Empire Strikes Back (1980)",
    "type": "Movie",
    "year": "1980",
    "videoId": "vi221753881",
    "videoTitle": "Official Trailer",
    "videoDescription": "After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.",
    "plot": "Luke Skywalker, Han Solo, Princess Leia and Chewbacca face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi Master's help will Luke survive when the Dark Side of the Force beckons him into the ultimate duel with Darth Vader.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BZGQzN2E0YmYtYzgxNS00NWM4LWFkY2ItZjBiNzgyZTM3ZmFmXkEyXkFqcGdeQWpvaG5oYXJ0._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi221753881",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi221753881/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0038650",
    "title": "It's a Wonderful Life",
    "fullTitle": "It's a Wonderful Life (1946)",
    "type": "Movie",
    "year": "1946",
    "videoId": "vi1101988121",
    "videoTitle": "It&apos;s a Wonderful Life",
    "videoDescription": "Home Video Trailer from Artisan",
    "plot": "George Bailey has spent his entire life giving of himself to the people of Bedford Falls. He has always longed to travel but never had the opportunity in order to prevent rich skinflint Mr. Potter from taking over the entire town. All that prevents him from doing so is George's modest building and loan company, which was founded by his generous father. But on Christmas Eve, George's Uncle Billy loses the business's $8,000 while intending to deposit it in the bank. Potter finds the misplaced money and hides it from Billy. When the bank examiner discovers the shortage later that night, George realizes that he will be held responsible and sent to jail and the company will collapse, finally allowing Potter to take over the town. Thinking of his wife, their young children, and others he loves will be better off with him dead, he contemplates suicide. But the prayers of his loved ones result in a gentle angel named Clarence coming to earth to help George, with the promise of earning his wings. He shows George what things would have been like if he had never been born.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNmUyMzVmNjgtMWQ1MS00OTkwLWEzMTktOTFlYmRiNmE1MWZhXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1101988121",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1101988121/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0120815",
    "title": "Saving Private Ryan",
    "fullTitle": "Saving Private Ryan (1998)",
    "type": "Movie",
    "year": "1998",
    "videoId": "vi1701906201",
    "videoTitle": "Saving Private Ryan",
    "videoDescription": "Trailer for this wartime drama",
    "plot": "Opening with the Allied invasion of Normandy on 6 June 1944, members of the 2nd Ranger Battalion under Cpt. Miller fight ashore to secure a beachhead. Amidst the fighting, two brothers are killed in action. Earlier in New Guinea, a third brother is KIA. Their mother, Mrs. Ryan, is to receive all three of the grave telegrams on the same day. The United States Army Chief of Staff, George C. Marshall, is given an opportunity to alleviate some of her grief when he learns of a fourth brother, Private James Ryan, and decides to send out 8 men (Cpt. Miller and select members from 2nd Rangers) to find him and bring him back home to his mother...",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BZjExYjU4OTAtMWM3NS00YzJkLWIzYjQtNTUxMWE5ZWY3MmVkXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi1701906201",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi1701906201/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0073486",
    "title": "One Flew Over the Cuckoo's Nest",
    "fullTitle": "One Flew Over the Cuckoo's Nest (1975)",
    "type": "Movie",
    "year": "1975",
    "videoId": "vi3943282969",
    "videoTitle": "Trailer",
    "videoDescription": "A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.",
    "plot": "McMurphy has a criminal past and has once again gotten himself into trouble and is sentenced by the court. To escape labor duties in prison, McMurphy pleads insanity and is sent to a ward for the mentally unstable. Once here, McMurphy both endures and stands witness to the abuse and degradation of the oppressive Nurse Ratched, who gains superiority and power through the flaws of the other inmates. McMurphy and the other inmates band together to make a rebellious stance against the atrocious Nurse.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNzcyYTlhYzgtOWY4Yi00NjZmLThhY2YtYWJjNjk2ODcyOWM2XkEyXkFqcGdeQXVyMjM4OTI2MTU@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi3943282969",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi3943282969/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0103064",
    "title": "Terminator 2: Judgment Day",
    "fullTitle": "Terminator 2: Judgment Day (1991)",
    "type": "Movie",
    "year": "1991",
    "videoId": "vi2748889369",
    "videoTitle": "Re-release Trailer",
    "videoDescription": "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten year old son, John Connor, from a more advanced cyborg.",
    "plot": "Over 10 years have passed since the first machine called The Terminator tried to kill Sarah Connor and her unborn son, John. The man who will become the future leader of the human resistance against the Machines is now a healthy young boy. However, another Terminator, called the T-1000, is sent back through time by the supercomputer Skynet. This new Terminator is more advanced and more powerful than its predecessor and its mission is to kill John Connor when he's still a child. However, Sarah and John do not have to face the threat of the T-1000 alone. Another Terminator (identical to the same model that tried and failed to kill Sarah Connor in 1984) is also sent back through time to protect them. Now, the battle for tomorrow has begun.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMjI0OTJlNTQtMzYyZi00MTBkLWEyMzItNWQwYWFhOWU1NDczXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2748889369",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2748889369/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0088763",
    "title": "Back to the Future",
    "fullTitle": "Back to the Future (1985)",
    "type": "Movie",
    "year": "1985",
    "videoId": "vi252380953",
    "videoTitle": "Back to the Future",
    "videoDescription": "Teaser trailer",
    "plot": "Marty McFly, a typical American teenager of the Eighties, is accidentally sent back to 1955 in a plutonium-powered DeLorean \"time machine\" invented by a slightly mad scientist. During his often hysterical, always amazing trip back in time, Marty must make certain his teenage parents-to-be meet and fall in love - so he can get back to the future.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYTE2MTY1MjktZTFmMS00MjI1LWFjYzUtNTVlZDVkZDNhMWEyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi252380953",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi252380953/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt2582802",
    "title": "Whiplash",
    "fullTitle": "Whiplash (2014)",
    "type": "Movie",
    "year": "2014",
    "videoId": "vi4006456345",
    "videoTitle": "Trailer #2",
    "videoDescription": "Andrew Neyman is an ambitious young jazz drummer, single-minded in his pursuit to rise to the top of his elite east coast music conservatory. Plagued by the failed writing career of his father, Andrew hungers day and night to become one of the greats. Terence Fletcher, an instructor equally known for his teaching talents as for his terrifying methods, leads the top jazz ensemble in the school. Fletcher discovers Andrew and transfers the aspiring drummer into his band, forever changing the young man&apos;s life. Andrew&apos;s passion to achieve perfection quickly spirals into obsession, as his ruthless teacher continues to push him to the brink of both his ability -- and his sanity. ",
    "plot": "Nineteen year old Andrew Niemann wants to be the greatest jazz drummer in the world, in a league with Buddy Rich. This goal is despite not coming from a pedigree of greatest, musical or otherwise, with Jim, his high school teacher father, being a failed writer. Andrew is starting his first year at Shaffer Conservatory of Music, the best music school in the United States. At Shaffer, being the best means being accepted to study under Terence Fletcher and being asked to play in his studio band, which represents the school at jazz competitions. Based on their less than positive first meeting, Andrew is surprised that Fletcher asks him to join the band, albeit in the alternate drummer position which he is more than happy to do initially. Andrew quickly learns that Fletcher operates on fear and intimidation, never settling for what he considers less than the best each and every time. Being the best in Fletcher's mind does not only entail playing well, but knowing that you're playing well and if not what you're doing wrong. His modus operandi creates an atmosphere of fear and of every man or woman for him/herself within the band. Regardless, Andrew works hard to be the best. He has to figure out his life priorities and what he is willing to sacrifice to be the best. The other question becomes how much emotional abuse he will endure by Fletcher to reach that greatness, which he may believe he can only achieve with the avenues opened up by Fletcher.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BMjMxNzAzMjY0NF5BMl5BanBnXkFtZTgwOTE4NTgyMjE@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi4006456345",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi4006456345/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0034583",
    "title": "Casablanca",
    "fullTitle": "Casablanca (1942)",
    "type": "Movie",
    "year": "1942",
    "videoId": "vi6095897",
    "videoTitle": "Casablanca",
    "videoDescription": "Trailer for the classic drama Casablanca starring Humphrey Bogart and Ingrid Bergman. ",
    "plot": "The story of Rick Blaine, a cynical world-weary ex-patriate who runs a nightclub in Casablanca, Morocco during the early stages of WWII. Despite the pressure he constantly receives from the local authorities, Rick's cafe has become a kind of haven for refugees seeking to obtain illicit letters that will help them escape to America. But when Ilsa, a former lover of Rick's, and her husband, show up to his cafe one day, Rick faces a tough challenge which will bring up unforeseen complications, heartbreak and ultimately an excruciating decision to make.",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BNzU0NDI1NjA1MF5BMl5BanBnXkFtZTcwMzM1MTgyMw@@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi6095897",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi6095897/imdb/embed",
    "errorMessage": ""
  },
  {
    "imDbId": "tt0407887",
    "title": "The Departed",
    "fullTitle": "The Departed (2006)",
    "type": "Movie",
    "year": "2006",
    "videoId": "vi2760573209",
    "videoTitle": "Home Video Trailer",
    "videoDescription": "Home Video Trailer from Warner Home Video",
    "plot": "In this crime-action tour de force, the South Boston state police force is waging war on Irish-American organized crime. Young undercover cop Billy Costigan is assigned to infiltrate the mob syndicate run by gangland chief Frank Costello. While Billy quickly gains Costello's confidence, Colin Sullivan, a hardened young criminal who has infiltrated the state police as an informer for the syndicate is rising to a position of power in the Special Investigation Unit. Each man becomes deeply consumed by their double lives, gathering information about the plans and counter-plans of the operations they have penetrated. But when it becomes clear to both the mob and the police that there is a mole in their midst, Billy and Colin are suddenly in danger of being caught and exposed to the enemy - and each must race to uncover the identity of the other man in time to save themselves. But is either willing to turn on their friends and comrades they've made during their long stints undercover?",
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BYzgwYWQ4NWItZjc3MC00Y2YyLWI2ZDgtMWE3ZjQxZDA2NzMyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_.jpg",
    "uploadDate": null,
    "link": "https://www.imdb.com/video/vi2760573209",
    "linkEmbed": "https://www.imdb.com/video/imdb/vi2760573209/imdb/embed",
    "errorMessage": ""
  }
];


function fillMovieCards() {
  let movies = await (await fetch('http://localhost:5600/api/movies')).json();

  for (let movie of movies) {
    html += `
    <div class="movie-card">
      <div class="movie-information">
        <h2>${movie.title}</h2>
        <p>${movie.plot}</p>
      </div>
      <div class="movie-posters">
        <img src="${movie.thumbnailUrl}" alt="${movie.fullTitle}">
      </div>
    </div>
    `;
  }

  document.querySelector('.movie-cards').innerHTML = html;
}


